name: Hakutaku
description: Hakutaku

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mifare_nfc_classic: ^0.2.2
  carousel_slider: ^3.0.0
  fluttertoast: ^8.0.3
  rflutter_alert: ^2.0.2
  qrscan: ^0.3.1
  webview_flutter: ^2.0.4
  flutter_datetime_picker: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

